<a href="https://colab.research.google.com/github/uppikaur/aml/blob/master/LabAssignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([[0], [1], [1], [0]])

In [3]:
"""
Activation Functions (Sigmoid & ReLU)
"""
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return (x > 0).astype(float)

In [4]:
class MLP:
    def __init__(self, input_size, hidden_layers, output_size, lr=0.1, activation='sigmoid'):
        self.lr = lr
        self.activation_name = activation

        # Architecture
        layers = [input_size] + hidden_layers + [output_size]

        # Initialize weights & biases
        self.weights = []
        self.biases = []

        for i in range(len(layers) - 1):
            self.weights.append(np.random.randn(layers[i], layers[i+1]))
            self.biases.append(np.zeros((1, layers[i+1])))

    def activation(self, x):
        if self.activation_name == 'sigmoid':
            return sigmoid(x)
        return relu(x)

    def activation_derivative(self, x):
        if self.activation_name == 'sigmoid':
            return sigmoid_derivative(x)
        return relu_derivative(x)

    # Forward Propagation
    def forward(self, X):
        self.activations = [X]

        for w, b in zip(self.weights, self.biases):
            z = np.dot(self.activations[-1], w) + b
            a = self.activation(z)
            self.activations.append(a)

        return self.activations[-1]

    # Loss (MSE)
    def loss(self, y_true, y_pred):
        return np.mean((y_true - y_pred) ** 2)

    # Backpropagation
    def backward(self, y_true):
        m = y_true.shape[0]

        deltas = [None] * len(self.weights)

        # Output layer error
        error = self.activations[-1] - y_true
        deltas[-1] = error * self.activation_derivative(self.activations[-1])

        # Hidden layers
        for i in reversed(range(len(deltas) - 1)):
            error = np.dot(deltas[i+1], self.weights[i+1].T)
            deltas[i] = error * self.activation_derivative(self.activations[i+1])

        # Update weights
        for i in range(len(self.weights)):
            self.weights[i] -= self.lr * np.dot(self.activations[i].T, deltas[i]) / m
            self.biases[i] -= self.lr * np.sum(deltas[i], axis=0, keepdims=True) / m

    # Training
    def train(self, X, y, epochs=10000, print_every=1000):
        for epoch in range(epochs):
            y_pred = self.forward(X)
            loss = self.loss(y, y_pred)

            self.backward(y)

            if epoch % print_every == 0:
                print(f"Epoch {epoch}, Loss: {loss:.6f}")

In [5]:
"""
Case 1: No Hidden Layer (Fails for XOR)
"""
print("\n--- No Hidden Layer ---")
mlp1 = MLP(input_size=2, hidden_layers=[], output_size=1, lr=0.1)
mlp1.train(X, y, epochs=5000)
print("Predictions:\n", mlp1.forward(X))


--- No Hidden Layer ---
Epoch 0, Loss: 0.338961
Epoch 1000, Loss: 0.252136
Epoch 2000, Loss: 0.250340
Epoch 3000, Loss: 0.250050
Epoch 4000, Loss: 0.250007
Predictions:
 [[0.5016302 ]
 [0.50023401]
 [0.50028105]
 [0.49888485]]


In [6]:
"""
Case 2: One Hidden Layer (2 Neurons)
"""
print("\n--- 1 Hidden Layer (2 neurons) ---")
mlp2 = MLP(2, [2], 1, lr=0.1, activation='sigmoid')
mlp2.train(X, y, epochs=10000)
print("Predictions:\n", mlp2.forward(X))


--- 1 Hidden Layer (2 neurons) ---
Epoch 0, Loss: 0.251552
Epoch 1000, Loss: 0.242579
Epoch 2000, Loss: 0.233848
Epoch 3000, Loss: 0.222252
Epoch 4000, Loss: 0.209966
Epoch 5000, Loss: 0.199524
Epoch 6000, Loss: 0.191841
Epoch 7000, Loss: 0.186469
Epoch 8000, Loss: 0.182649
Epoch 9000, Loss: 0.179693
Predictions:
 [[0.13594507]
 [0.63361969]
 [0.65790093]
 [0.66155633]]


In [7]:
"""
Case 3: One Hidden Layer (4 Neurons)
"""
print("\n--- 1 Hidden Layer (4 neurons) ---")
mlp3 = MLP(2, [4], 1, lr=0.1, activation='sigmoid')
mlp3.train(X, y, epochs=10000)
print("Predictions:\n", mlp3.forward(X))



--- 1 Hidden Layer (4 neurons) ---
Epoch 0, Loss: 0.257773
Epoch 1000, Loss: 0.252520
Epoch 2000, Loss: 0.250226
Epoch 3000, Loss: 0.248260
Epoch 4000, Loss: 0.245222
Epoch 5000, Loss: 0.239388
Epoch 6000, Loss: 0.228829
Epoch 7000, Loss: 0.212230
Epoch 8000, Loss: 0.190411
Epoch 9000, Loss: 0.166060
Predictions:
 [[0.23269048]
 [0.53744638]
 [0.74251971]
 [0.47148822]]


In [8]:
"""
Case 4: Deep Network (4 Hidden Layers)
"""
print("\n--- 4 Hidden Layers ---")
mlp4 = MLP(2, [4, 4, 4, 4], 1, lr=0.1, activation='sigmoid')
mlp4.train(X, y, epochs=10000)
print("Predictions:\n", mlp4.forward(X))


--- 4 Hidden Layers ---
Epoch 0, Loss: 0.296887
Epoch 1000, Loss: 0.249438
Epoch 2000, Loss: 0.249241
Epoch 3000, Loss: 0.248969
Epoch 4000, Loss: 0.248586
Epoch 5000, Loss: 0.248033
Epoch 6000, Loss: 0.247218
Epoch 7000, Loss: 0.245979
Epoch 8000, Loss: 0.244026
Epoch 9000, Loss: 0.240796
Predictions:
 [[0.43756011]
 [0.49543137]
 [0.54444499]
 [0.53576961]]


In [9]:
"""
Activation Function Comparison
"""
print("\n--- Using ReLU ---")
mlp_relu = MLP(2, [4], 1, lr=0.01, activation='relu')
mlp_relu.train(X, y, epochs=10000)
print("Predictions:\n", mlp_relu.forward(X))



--- Using ReLU ---
Epoch 0, Loss: 0.500000
Epoch 1000, Loss: 0.500000
Epoch 2000, Loss: 0.500000
Epoch 3000, Loss: 0.500000
Epoch 4000, Loss: 0.500000
Epoch 5000, Loss: 0.500000
Epoch 6000, Loss: 0.500000
Epoch 7000, Loss: 0.500000
Epoch 8000, Loss: 0.500000
Epoch 9000, Loss: 0.500000
Predictions:
 [[0.]
 [0.]
 [0.]
 [0.]]


In [10]:
"""
Learning Rate Experiment
"""
for lr in [0.001, 0.01, 0.1]:
    print(f"\n--- Learning Rate: {lr} ---")
    model = MLP(2, [4], 1, lr=lr)
    model.train(X, y, epochs=5000)
    print("Predictions:\n", model.forward(X))


--- Learning Rate: 0.001 ---
Epoch 0, Loss: 0.259286
Epoch 1000, Loss: 0.259162
Epoch 2000, Loss: 0.259040
Epoch 3000, Loss: 0.258919
Epoch 4000, Loss: 0.258800
Predictions:
 [[0.49588293]
 [0.57004774]
 [0.41665454]
 [0.51349854]]

--- Learning Rate: 0.01 ---
Epoch 0, Loss: 0.267201
Epoch 1000, Loss: 0.250726
Epoch 2000, Loss: 0.246809
Epoch 3000, Loss: 0.244000
Epoch 4000, Loss: 0.241413
Predictions:
 [[0.36384069]
 [0.55582602]
 [0.51027246]
 [0.62161684]]

--- Learning Rate: 0.1 ---
Epoch 0, Loss: 0.292609
Epoch 1000, Loss: 0.248700
Epoch 2000, Loss: 0.246478
Epoch 3000, Loss: 0.242473
Epoch 4000, Loss: 0.234116
Predictions:
 [[0.47080847]
 [0.48967476]
 [0.58960684]
 [0.46399078]]


In [11]:
mlp = MLP(input_size=2, hidden_layers=[4], output_size=1, lr=0.1)
mlp.train(X, y, epochs=10000)

print("Predictions:")
print(mlp.forward(X))

Epoch 0, Loss: 0.250953
Epoch 1000, Loss: 0.242804
Epoch 2000, Loss: 0.233769
Epoch 3000, Loss: 0.218777
Epoch 4000, Loss: 0.198063
Epoch 5000, Loss: 0.174181
Epoch 6000, Loss: 0.148616
Epoch 7000, Loss: 0.121036
Epoch 8000, Loss: 0.092867
Epoch 9000, Loss: 0.067853
Predictions:
[[0.17455323]
 [0.78647385]
 [0.78200032]
 [0.26717223]]
